In [1]:
import numpy as np

In [3]:
arr1=np.array([])
arr1

array([], dtype=float64)

In [5]:
list=[1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
a=np.array(list)
a

array([1, 2, 3, 4, 5])

In [10]:
type(a)

numpy.ndarray

In [11]:
a.size

5

In [12]:
a.shape

(5,)

In [13]:
a.ndim

1

In [14]:
matrix=[[1,3,5,7],[2,4,6,8],[4,7,3,0]]
matrix

[[1, 3, 5, 7], [2, 4, 6, 8], [4, 7, 3, 0]]

In [16]:
b=np.array(matrix)
b

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [4, 7, 3, 0]])

In [19]:
b.ndim

2

In [20]:
b.size


12

In [21]:
b.shape

(3, 4)

In [23]:
type(b)

numpy.ndarray

In [24]:
matrix=[[1,3,5,7],[2,4,6,8],[4,7,3,0],[1,2,3,4],[9,6,3,0]]
matrix

[[1, 3, 5, 7], [2, 4, 6, 8], [4, 7, 3, 0], [1, 2, 3, 4], [9, 6, 3, 0]]

In [26]:
d=np.array(matrix)

In [27]:
d

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [4, 7, 3, 0],
       [1, 2, 3, 4],
       [9, 6, 3, 0]])

In [28]:
d.ndim

2

In [29]:
d.shape

(5, 4)

In [30]:
d.size

20

In [32]:
matrix3=[[[1,3,5,7],[2,4,6,8],[4,7,3,0],[1,2,3,4],[9,6,3,0]]]
matrix3

[[[1, 3, 5, 7], [2, 4, 6, 8], [4, 7, 3, 0], [1, 2, 3, 4], [9, 6, 3, 0]]]

In [37]:
arr1=np.array(matrix3)
arr1

array([[[1, 3, 5, 7],
        [2, 4, 6, 8],
        [4, 7, 3, 0],
        [1, 2, 3, 4],
        [9, 6, 3, 0]]])

In [42]:
arr1.ndim

3

In [43]:
arr1.shape

(1, 5, 4)

Build in methods

In [41]:
# 1) Reshape

In [49]:
arr2=arr1.reshape((1,4,5))

In [50]:
arr2

array([[[1, 3, 5, 7, 2],
        [4, 6, 8, 4, 7],
        [3, 0, 1, 2, 3],
        [4, 9, 6, 3, 0]]])

In [51]:
arr2.size

20

In [52]:
arr2.shape

(1, 4, 5)

In [53]:
arr2.ndim

3

In [55]:
# 2) arange

In [62]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [74]:
np.arange(3,33,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [78]:
np.arange(100,0,-9)

array([100,  91,  82,  73,  64,  55,  46,  37,  28,  19,  10,   1])

In [79]:
# 3) zeros and ones

In [80]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [88]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [92]:
# 4)linspace

In [94]:
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [106]:
np.linspace(1,10,12) ##(1,10,12) here 1-> is starting point,10 is end point and 
                       12 is the no that we want values from start to end

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [109]:
np.linspace(0,10,retstep=True) #start #end #default=50 values

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 0.20408163265306123)

In [113]:
np.linspace(12,140,19,retstep=True)

(array([ 12.        ,  19.11111111,  26.22222222,  33.33333333,
         40.44444444,  47.55555556,  54.66666667,  61.77777778,
         68.88888889,  76.        ,  83.11111111,  90.22222222,
         97.33333333, 104.44444444, 111.55555556, 118.66666667,
        125.77777778, 132.88888889, 140.        ]),
 7.111111111111111)

In [115]:
# 5) eye: create identity matrix

In [116]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
# 6)Broadcasting an array"

In [120]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [122]:
a.dtype

dtype('float64')

In [135]:
a*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [125]:
b=a*5-2
b

array([[3., 3., 3.],
       [3., 3., 3.]])

In [128]:
b=a*5-0.6
b

array([[4.4, 4.4, 4.4],
       [4.4, 4.4, 4.4]])

In [130]:
b=np.array(a*5-0.6,dtype='int')
b

array([[4, 4, 4],
       [4, 4, 4]])

In [137]:
b.dtype

dtype('int32')

In [138]:
type(b)

numpy.ndarray

In [139]:
# 7) cppy

In [141]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [143]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [144]:
arr**arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408])

In [146]:
arr1=arr
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr1[8:]=0
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0])

In [166]:
arr1[:8]=4
arr1

array([4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0])

In [167]:
arr

array([4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0])

In [168]:
arr2=arr.copy()

In [169]:
arr2

array([4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0])