In [1]:
import numpy as np

In [6]:
arr=np.arange(0,43)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42])

In [7]:
len(arr)

43

In [9]:
arr.size

43

In [10]:
arr.shape

(43,)

In [11]:
arr[-1]

42

In [13]:
arr[::-1] #reverse

array([42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1,  0])

In [15]:
arr[0:26:5]

array([ 0,  5, 10, 15, 20, 25])

In [16]:
#filtering conditions

In [20]:
arr1=np.array([312,66,89,23,1,674,83,43])
arr1

array([312,  66,  89,  23,   1, 674,  83,  43])

In [21]:
arr1<100

array([False,  True,  True,  True,  True, False,  True,  True])

In [28]:
arr1>100

array([ True, False, False, False, False,  True, False, False])

In [29]:
np.where(arr1<100)  # where function gives outputs index location

(array([1, 2, 3, 4, 6, 7], dtype=int64),)

In [30]:
np.where(arr1>100)

(array([0, 5], dtype=int64),)

indexing 2d matrix

In [31]:
arr_2d=np.array(([1,3,5],[2,4,6],[7,8,9]))
arr_2d

array([[1, 3, 5],
       [2, 4, 6],
       [7, 8, 9]])

In [32]:
arr_2d[1]

array([2, 4, 6])

In [34]:
arr_2d[0:2]

array([[1, 3, 5],
       [2, 4, 6]])

In [36]:
arr_2d[0:,:2]

array([[1, 3],
       [2, 4],
       [7, 8]])

In [39]:
arr_2d[2,1]

8

In [47]:
arr_2d.shape

(3, 3)

fancy indexing

In [53]:
arr2=np.ones((5,5))

In [54]:
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
arr3=np.zeros(arr2.shape)
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])